apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
namespace: sns
resources:
- ns.yaml
- redis.yaml
- payments.yaml
- subscriptions.yaml
- payments-configmap.yaml
- subscriptions-configmap.yaml
- secrets.yaml
