apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-configmap
  namespace: sns
  labels:
    app: payments
data:
  config.production.json: |
    {
        "server_port": 3000,
        "redis_host": "redis",
        "redis_port": 6379,
        "log_file": "/opt/sns/logs/logfile.txt"
    }

