apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sns-role
  namespace: sns
rules:
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  name: sns-sa-rolebinding
  namespace: sns
roleRef:
  kind: Role
  name: sns-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: sns-sa
    namespace: sns

