---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sns-redis-pvc
  namespace: sns
spec:
  storageClassName: mylocalstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sns-redis-pv
  namespace: sns
spec:
  storageClassName: mylocalstorage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data2x/redis
    type: DirectoryOrCreate

